@php($isCreate = $prefix === 'create')
<div class="row g-3">
    <div class="col-12"><label class="form-label" for="{{ $prefix }}Title">Título o nombre <span class="text-danger">*</span></label><div class="input-group"><input class="form-control d-none flex-grow-0" data-myth-title-prefix type="text" value="Mito:" aria-label="Prefijo fijo del título" style="width: 5rem" disabled><input class="form-control" id="{{ $prefix }}Title" name="title" maxlength="255" required @if($isCreate) value="{{ old('title') }}" @endif></div></div>
    <div class="col-12 d-none" data-story-field><label class="form-label" for="{{ $prefix }}Subtitle">Identificación o descripción de la persona</label><input class="form-control" id="{{ $prefix }}Subtitle" name="subtitle" maxlength="255" placeholder="Ej.: Madre de paciente trasplantada" @if($isCreate) value="{{ old('subtitle') }}" @endif></div>
    <div class="col-12"><label class="form-label" for="{{ $prefix }}BodyEditor">Contenido <span class="text-danger">*</span></label><input id="{{ $prefix }}Body" name="body" type="hidden" value="{{ $isCreate ? old('body') : '' }}"><trix-editor class="cms-trix-editor" id="{{ $prefix }}BodyEditor" input="{{ $prefix }}Body" placeholder="Escribe el contenido y selecciona una frase para agregarle un enlace."></trix-editor><small class="form-text">Para crear un enlace, selecciona el texto y utiliza el botón de cadena.</small></div>
    <div class="col-12 d-none" data-legal-field><label class="form-label" for="{{ $prefix }}Image">Imagen relacionada opcional</label><input class="form-control" id="{{ $prefix }}Image" name="image" type="file" accept="image/jpeg,image/png,image/webp" data-cms-crop-input><div class="alert alert-light border mt-2 mb-0" role="note"><strong>Formatos de origen:</strong> JPG, PNG o WebP, hasta 15 MB.<br>Después de seleccionarla podrás recortarla. El resultado será un JPG de 1600×900 px, proporción 16:9 y máximo 2 MB.</div><div class="cms-crop-result d-none mt-2" data-cms-crop-result></div><img class="cms-crop-preview d-none mt-2" data-cms-crop-preview alt="Vista previa de la imagen recortada"><p class="cms-current-image mb-0 mt-2" id="{{ $prefix }}CurrentImage"></p><label class="form-label mt-2" for="{{ $prefix }}ImageAlt">Descripción accesible de la imagen</label><input class="form-control" id="{{ $prefix }}ImageAlt" name="image_alt" maxlength="255" placeholder="Describe brevemente lo que muestra la imagen">@if(!$isCreate)<div class="form-check mt-2"><input class="form-check-input" id="editRemoveLegalMedia" name="remove_media" type="checkbox" value="1"><label class="form-check-label" for="editRemoveLegalMedia">Retirar la imagen actual</label></div>@endif</div>
    <div class="col-12 d-none" data-story-field><label class="form-label" for="{{ $prefix }}Video">Video corto opcional</label><input class="form-control" id="{{ $prefix }}Video" name="video" type="file" accept="video/mp4,video/quicktime,.mp4,.mov"><div class="alert alert-light border mt-2 mb-0" role="note"><strong>Formatos aceptados:</strong> MP4 o MOV, horizontal o vertical.<br><strong>Requisitos:</strong> máximo 25 MB y duración máxima de 90 segundos. Los videos que lo requieran se convertirán a MP4 de 1280×720 con H.264 y AAC. Los videos verticales conservarán la imagen completa y tendrán bandas laterales.</div><p class="cms-current-video mb-0 mt-2" id="{{ $prefix }}CurrentVideo"></p>@if(!$isCreate)<div class="form-check mt-2"><input class="form-check-input" id="editRemoveStoryMedia" name="remove_media" type="checkbox" value="1"><label class="form-check-label" for="editRemoveStoryMedia">Retirar el video actual</label></div>@endif</div>
    <div class="col-sm-4"><label class="form-label" for="{{ $prefix }}SortOrder">Orden <span class="text-danger">*</span></label><input class="form-control" id="{{ $prefix }}SortOrder" name="sort_order" type="number" min="0" max="9999" required value="{{ $isCreate ? old('sort_order', 1) : '' }}"></div>
    <div class="col-sm-8 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" id="{{ $prefix }}Visible" name="is_visible" type="checkbox" value="1" @checked($isCreate ? old('is_visible', true) : false)><label class="form-check-label" for="{{ $prefix }}Visible">Mostrar en el portal público</label></div></div>
</div>
